"""New Migration

Revision ID: 80aa916f01cd
Revises: 
Create Date: 2023-04-18 05:47:01.225840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80aa916f01cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relative_path', sa.String(), nullable=True),
    sa.Column('output', sa.Integer(), nullable=True),
    sa.Column('emotion', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_table('users',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('username', sa.String(length=50), nullable=False),
    # sa.Column('email', sa.String(length=120), nullable=False),
    # sa.Column('password', sa.String(length=128), nullable=False),
    # sa.Column('name', sa.String(), nullable=True),
    # sa.Column('age', sa.Integer(), nullable=True),
    # sa.Column('gender', sa.String(), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('email'),
    # sa.UniqueConstraint('username')
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('records')
    # ### end Alembic commands ###
