"""New Migration

Revision ID: e44ffab5e774
Revises: e6bd171c53d1
Create Date: 2023-04-19 14:09:43.523325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e44ffab5e774'
down_revision = 'e6bd171c53d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('relative_path', sa.String(), nullable=True),
    sa.Column('output', sa.Integer(), nullable=True),
    sa.Column('emotion', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('index')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    # ### end Alembic commands ###
